### ISSUE TITLE
Update development guide to explain decorative images should be CSS backgrounds, not img tags

### ISSUE THREAD

**Issue by gtvj** [nationalarchives/development-guide-and-peer-reviews#22]
The DAC report has identified an instance where a decorative image has been implemented using an `<img>` tag. We should be explicity about this in the front-end-development-guide so that everyone (including new starters) and 3rd parties are aware.

**Comment by AshGDS** [comment]
@gtvj This is ready for a pull request - who would be most appropriate to assign it to?

Thanks
